apiVersion: v1
kind: ReplicationController
metadata:
  name: staging-bible-api-v1.0.1  # Name of the RC
spec:
  replicas: 3                # How many copies of your pod you want to run
  selector:                  # Set of selectors for matching pods this RC should maintain
    name: bible-api
    environment: staging
    role: app
    deployment: v1.0.1
  template:                  # Pod template to use when this RC creates pods
    metadata:
      labels:                # Labels to use for the pods created by this RC
        name: bible-api
        environment: staging
        role: app
        deployment: v1.0.1
    spec:
      terminationGracePeriodSeconds: 15  # How much time to give your pods before force killing them
      imagePullSecrets:                  # Keys needed by docker to pull private repository images from docker hub
        - name: dockerhubkey
      containers:                        # List of containser in this pod
        - name: app                      # Name of the container
          image: sovee/bible-api:latest          # Image to use for the container
          command:                       # Command to execute when starting the container (Not needed if you have a CMD in your Dockerfile instead)
            - nodemon
            - server.js
          ports:                         # List of ports your app will use
            - name: app                  # Name for the port (Not required if there is only 1 port)
              containerPort: 3000        # Port your app will listen on
          imagePullPolicy: Always        # Tells docker to always pull the image instead of using local cache of the image (good if your using a tag like :latest)
          env:                           # List of environment variables to set in the container
            - name: AUTH_HOST
              value: "http://staging-auth"
            - name: AUTH_TOKEN
              value: "fe56002db2632cd72daff4ac496aac1cfec7577b"
            - name: DB_HOST
              value: 'c457.candidate.55.mongolayer.com:10457,candidate.54.mongolayer.com:10342,candidate.55.mongolayer.com:10457'
            - name: DB_DATABASE
              value: 'staging-bible-api'
            - name: DB_USERNAME
              value: 'bible-api-data'
            - name: DB_PASSWORD
              value: '0cc36adff87b434a841c7e8d7cccc702'
            - name: DB_REPLICA_SET
              value: 'set-5630eec9e66bf67594001734'
            - name: PARALLEL_HOST
              value: "http://staging-parallel-api"
